substitutions:
  name: esphome-web-13d18e
  friendly_name: DashButton1

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  safe_mode: true
  port: 8266
  password: !secret ota_password

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  #ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
#captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

mqtt:
  broker: 192.168.10.102
  username: mqtt
  password: !secret mqtt_password
  topic_prefix: /DashButton1
  birth_message:
   topic: DashButton1/buttonPressed
   payload: "true"
  will_message:
   topic: DashButton1/buttonPressed
   payload: "false"
  
deep_sleep:
  run_duration: 2s
